name: Run Pester Tests
permissions:
  contents: read
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Perform a Pester test from the ETypeDetection.Tests.ps1
        shell: pwsh
        run: |
          Invoke-Pester ./scripts/ETypeDetection.Tests.ps1 -Output Detailed -Passthru
