name: Run Pester Tests
permissions:
  contents: read
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Perform a Pester test from the ETypeDetection.Tests.ps1
        shell: pwsh
        run: |
          Invoke-Pester ./scripts/ETypeDetection.Tests.ps1 -Output Detailed -Passthru
